print("===================================================")
print("                  |BMI Calculator|                 ")
print("===================================================")
print(" ")
Name = input("Enter your first name : ")
Surname = input("Enter your last name : ")
YOB = int(input("Year of birth : "))
Age = 2022-YOB
Height = float(input("Enter height(meters) : "))
Weight = float(input("Enter weight(kg) : "))
BMI = Weight/(Height*Height)
print(" ")
print("===================================================")
print("                 |BMI  Weight Status|              ")
print("===================================================")
print(" ")
print("      Below 18.5              Underweight ")
print("      18.5 –24.9              Healthy Weight")
print("      25.0 –29.9              Overweight")
print("      30.0 and Above          Obesity    ")
print(" ")
print("---------------------------------------------------")
print("Name : %s %s"% (Name,Surname))
print("Height : %.2f"% Height)
print("Weight : %.2f"% Weight)
print("Age: %d"% Age)
print(" ")
print("****************** ")
print("Your BMI : %.2f"% BMI)
print("****************** ")